/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gmplib_gmpjni_MPFR_mpfr_rnd_t */

#ifndef _Included_org_gmplib_gmpjni_MPFR_mpfr_rnd_t
#define _Included_org_gmplib_gmpjni_MPFR_mpfr_rnd_t
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
