/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gmplib_gmpjni_MPFR */

#ifndef _Included_org_gmplib_gmpjni_MPFR
#define _Included_org_gmplib_gmpjni_MPFR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1version
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_str
 * Signature: (JLjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1str
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_str
 * Signature: (Lorg/gmplib/gmpjni/GMP/MutableInteger;JIJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1str
  (JNIEnv *, jclass, jobject, jlong, jint, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_d_2exp
 * Signature: (Lorg/gmplib/gmpjni/GMP/MutableInteger;JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1d_12exp
  (JNIEnv *, jclass, jobject, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_frexp
 * Signature: (Lorg/gmplib/gmpjni/GMP/MutableInteger;JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1frexp
  (JNIEnv *, jclass, jobject, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_lgamma
 * Signature: (JLorg/gmplib/gmpjni/GMP/MutableInteger;JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1lgamma
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_remquo
 * Signature: (JLorg/gmplib/gmpjni/GMP/MutableInteger;JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1remquo
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_emin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1emin
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_emin
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1emin
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_emin_min
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1emin_1min
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_emin_max
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1emin_1max
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_emax
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1emax
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_emax
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1emax
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_emax_min
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1emax_1min
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_emax_max
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1emax_1max
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_default_rounding_mode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1default_1rounding_1mode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_default_rounding_mode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1default_1rounding_1mode
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_clear_flags
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1clear_1flags
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_clear_underflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1clear_1underflow
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_clear_overflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1clear_1overflow
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_clear_divby0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1clear_1divby0
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_clear_nanflag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1clear_1nanflag
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_clear_inexflag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1clear_1inexflag
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_clear_erangeflag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1clear_1erangeflag
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_underflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1underflow
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_overflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1overflow
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_divby0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1divby0
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_nanflag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1nanflag
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_inexflag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1inexflag
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_erangeflag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1erangeflag
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_underflow_p
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1underflow_1p
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_overflow_p
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1overflow_1p
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_divby0_p
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1divby0_1p
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_nanflag_p
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1nanflag_1p
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_inexflag_p
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1inexflag_1p
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_erangeflag_p
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1erangeflag_1p
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_check_range
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1check_1range
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_prec_round
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1prec_1round
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_can_round
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1can_1round
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_min_prec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1min_1prec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_exp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1exp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_exp
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1exp
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_prec
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1prec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_prec
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1prec
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_prec_raw
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1prec_1raw
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_default_prec
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1default_1prec
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_default_prec
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1default_1prec
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_d
 * Signature: (JDI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1d
  (JNIEnv *, jclass, jlong, jdouble, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_flt
 * Signature: (JFI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1flt
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_z
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1z
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_z_2exp
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1z_12exp
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_nan
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1nan
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_inf
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1inf
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_zero
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1zero
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_f
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1f
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_f
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1f
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_si
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1si
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_ui
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1ui
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_si_2exp
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1si_12exp
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_ui_2exp
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1ui_12exp
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set_q
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set_1q
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_abs
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1abs
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_set
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1set
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_neg
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1neg
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_signbit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1signbit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_setsign
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1setsign
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_copysign
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1copysign
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_z_2exp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1z_12exp
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_flt
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1flt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_d
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1d
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_d1
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1d1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_si
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1si
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_ui
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1ui
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_get_z
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1get_1z
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_urandom
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1urandom
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_grandom
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1grandom
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_urandomb
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1urandomb
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_nextabove
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1nextabove
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_nextbelow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1nextbelow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_nexttoward
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1nexttoward
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_pow
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1pow
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_pow_si
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1pow_1si
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_pow_ui
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1pow_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_ui_pow_ui
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1ui_1pow_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_ui_pow
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1ui_1pow
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_pow_z
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1pow_1z
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sqrt
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sqrt
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sqrt_ui
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sqrt_1ui
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_rec_sqrt
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1rec_1sqrt
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_add
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1add
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sub
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sub
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_mul
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1mul
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_div
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1div
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_add_ui
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1add_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sub_ui
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sub_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_ui_sub
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1ui_1sub
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_mul_ui
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1mul_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_div_ui
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1div_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_ui_div
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1ui_1div
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_add_si
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1add_1si
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sub_si
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sub_1si
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_si_sub
 * Signature: (JIJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1si_1sub
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_mul_si
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1mul_1si
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_div_si
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1div_1si
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_si_div
 * Signature: (JIJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1si_1div
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_add_d
 * Signature: (JJDI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1add_1d
  (JNIEnv *, jclass, jlong, jlong, jdouble, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sub_d
 * Signature: (JJDI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sub_1d
  (JNIEnv *, jclass, jlong, jlong, jdouble, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_d_sub
 * Signature: (JDJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1d_1sub
  (JNIEnv *, jclass, jlong, jdouble, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_mul_d
 * Signature: (JJDI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1mul_1d
  (JNIEnv *, jclass, jlong, jlong, jdouble, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_div_d
 * Signature: (JJDI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1div_1d
  (JNIEnv *, jclass, jlong, jlong, jdouble, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_d_div
 * Signature: (JDJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1d_1div
  (JNIEnv *, jclass, jlong, jdouble, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sqr
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sqr
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_const_pi
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1const_1pi
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_const_log2
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1const_1log2
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_const_euler
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1const_1euler
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_const_catalan
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1const_1catalan
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_agm
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1agm
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_log
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1log
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_log2
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1log2
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_log10
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1log10
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_log1p
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1log1p
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_exp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1exp
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_exp2
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1exp2
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_exp10
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1exp10
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_expm1
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1expm1
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_eint
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1eint
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_li2
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1li2
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cmp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cmp
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cmp_d
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cmp_1d
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cmpabs
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cmpabs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cmp_ui
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cmp_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cmp_si
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cmp_1si
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cmp_ui_2exp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cmp_1ui_12exp
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cmp_si_2exp
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cmp_1si_12exp
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_reldiff
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1reldiff
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_eq
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1eq
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sgn
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sgn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_mul_2exp
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1mul_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_div_2exp
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1div_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_mul_2ui
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1mul_12ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_div_2ui
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1div_12ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_mul_2si
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1mul_12si
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_div_2si
 * Signature: (JJII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1div_12si
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_rint
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1rint
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_round
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1round
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_trunc
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1trunc
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_ceil
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1ceil
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_floor
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1floor
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_rint_round
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1rint_1round
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_rint_trunc
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1rint_1trunc
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_rint_ceil
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1rint_1ceil
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_rint_floor
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1rint_1floor
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_frac
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1frac
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_modf
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1modf
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_remainder
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1remainder
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fmod
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fmod
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fits_ulong_p
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fits_1ulong_1p
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fits_slong_p
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fits_1slong_1p
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fits_uint_p
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fits_1uint_1p
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fits_sint_p
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fits_1sint_1p
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fits_ushort_p
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fits_1ushort_1p
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fits_sshort_p
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fits_1sshort_1p
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fits_uintmax_p
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fits_1uintmax_1p
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fits_intmax_p
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fits_1intmax_1p
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_swap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1swap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_nan_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1nan_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_inf_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1inf_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_number_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1number_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_integer_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1integer_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_zero_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1zero_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_regular_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1regular_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_greater_p
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1greater_1p
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_greaterequal_p
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1greaterequal_1p
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_less_p
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1less_1p
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_lessequal_p
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1lessequal_1p
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_lessgreater_p
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1lessgreater_1p
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_equal_p
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1equal_1p
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_unordered_p
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1unordered_1p
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_atanh
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1atanh
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_acosh
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1acosh
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_asinh
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1asinh
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cosh
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cosh
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sinh
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sinh
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_tanh
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1tanh
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sinh_cosh
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sinh_1cosh
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sech
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sech
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_csch
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1csch
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_coth
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1coth
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_acos
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1acos
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_asin
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1asin
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_atan
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1atan
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sin
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sin
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sin_cos
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sin_1cos
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cos
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cos
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_tan
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1tan
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_atan2
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1atan2
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sec
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sec
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_csc
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1csc
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cot
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cot
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_hypot
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1hypot
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_erf
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1erf
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_erfc
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1erfc
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cbrt
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cbrt
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_root
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1root
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_gamma
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1gamma
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_lngamma
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1lngamma
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_digamma
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1digamma
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_zeta
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1zeta
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_zeta_ui
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1zeta_1ui
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fac_ui
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fac_1ui
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_j0
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1j0
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_j1
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1j1
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_jn
 * Signature: (JIJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1jn
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_y0
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1y0
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_y1
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1y1
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_yn
 * Signature: (JIJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1yn
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_ai
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1ai
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_min
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1min
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_max
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1max
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_dim
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1dim
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_mul_z
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1mul_1z
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_div_z
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1div_1z
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_add_z
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1add_1z
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sub_z
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sub_1z
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_z_sub
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1z_1sub
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cmp_z
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cmp_1z
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_mul_q
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1mul_1q
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_div_q
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1div_1q
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_add_q
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1add_1q
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_sub_q
 * Signature: (JJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1sub_1q
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cmp_q
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cmp_1q
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_cmp_f
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1cmp_1f
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fma
 * Signature: (JJJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fma
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_fms
 * Signature: (JJJJI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1fms
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_free_cache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1free_1cache
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_MPFR
 * Method:    native_mpfr_subnormalize
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_MPFR_native_1mpfr_1subnormalize
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
